mqas:
  web:
    url: http://127.0.0.1:${server.port}/
server:
  port: 8892
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/manamanam
    username: postgres
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: mqas_test 
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: 5963$Kjohn&
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
    username: mehdi.z.jorshari@gmail.com
