apiVersion: v1
kind: Service
metadata:
  name: solr-loader-srv
  labels:
    app: solr-loader
spec:
  ports:
    - port: 5536
  selector:
    app: solr-loader
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-loader
  labels:
    app: solr-loader
spec:
  selector:
    matchLabels:
      app: solr-loader
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: solr-loader
    spec:
      containers:
      - image: mehdizj2000/solr-loader
        name: solr-loader
        env:
        - name: SPRING_BATCH_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef: 
              name: solr-spring-app-config
              key: batchJDBCUrl 
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef: 
              name: solr-spring-app-config
              key: gnafJDBCUrl 
        - name: SPRING_BATCH_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: GNAF_ZK-SERVERS
          valueFrom: 
            configMapKeyRef: 
              name: solr-cluster-config
              key: zkHost
