spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/manamanam
    username: postgres
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: mqas_test 
    hibernate:
      ddl-auto: create
---
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:4455/app_mqas?createDatabaseIfNotExist=true
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
