--- 
spring: 
  batch: 
    datasource: 
      password: 123456
      url: "jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=batchstuff"
      username: postgres
    initialize-schema: always
    job: 
      enabled: false
  datasource: 
    password: 123456
    url: "jdbc:postgresql://127.0.0.1:5432/postgres"
    username: postgres
  jpa: 
    generate-ddl: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        default_schema: gnaf_home
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  
server:
  port: 5536
gnaf:
  zk-servers: node01:2181,node02:2181,node03:2181